### ISSUE TITLE
problems running the oy.exe file on Windows 64 bit

### ISSUE THREAD

**Issue by yellow-panther** [johncheetham/jcchess#2]
Hello John and Tamás, I have installed: 
https://www.python.org/ftp/python/3.4.4/python-3.4.4.amd64.msi

https://sourceforge.net/projects/pygobjectwin32/files/pygi-aio-3.24.1_rev1-setup_049a323fe25432b10f7e9f543b74598d4be74a39.exe/download

and tick on the following packages 
Base packages
GDK-Pixbuf
GTK+ 3.x
Pango

Then I looked at: https://github.com/johncheetham/jcchess/blob/master/.gitignore

The extracted application is JCchess  situated here:

C:\User\NRL\Downloads\jcchess-master\jcchess.master (The folder setup-tools is extracted too!)

After starting Windows console-mode with cmd.exe I inserted
C:\User\NRL\Downloads\jcchess-master\jcchess.master\python.exe python run.py

but nothing happened : system cannot find the specified path! What went wrong?

**Could you host an all-in-one solution for Windows 64 bit-systems please:
with pre-configurated pygi-aio-3.24.1_rev1, python3.44. msi and jcchess for download 

It seems that JCchess is originally built for Linux distributions.**

**Comment by johncheetham** [comment]
Yes I tested it on Linux and haven't tried windows until now.
I created a Readme-windows.txt file with instructions for installing on windows (see updated issue #1).
An all in one installer (as in just one msi file) is a good idea but I don't have the knowledge to do that on windows. I think it would be a quite big file and probably would take some time to do.
gbtami I think you did this already on pychess?

**Comment by gbtami** [comment]
@johncheetham yes, pychess uses  cx_freezee to create .msi with `python setup.py bdist_msi`.
Just note that it needs some extra work here and there in the code base, because in a "frozen" app some path related stuff needs special handling. (If one interested about these search for "frozen" in pychess sources.)
If you don't want to deal with "frozen" app problems, you can use NSIS to create a .exe installer.

**Comment by johncheetham** [comment]
Thanks for the tips @gbtami I used [pynsist](https://pynsist.readthedocs.io/en/latest/). By the way there seems to be a problem with pychess.org website. I get either a blank page or a godaddy page.

@yellow-panther I created all-in-one installer [here](https://drive.google.com/open?id=0B91ZDRXsSFY9TUNkUU9IVHFiSmc).

**Comment by johncheetham** [comment]
Windows builds are now available on the website and I have updated the git repo with the files/instructions for creating the installers using pynsist.
